package com.example.aquiethours.util

import android.util.Base64
import com.example.aquiethours.data.Schedule
import com.google.gson.Gson
import com.google.gson.reflect.TypeToken
import java.io.ByteArrayOutputStream
import java.time.DayOfWeek
import java.util.zip.Deflater
import java.util.zip.Inflater

data class SharedScheduleEntry(
    val day: DayOfWeek,
    val startHour: Int,
    val startMinute: Int,
    val endHour: Int,
    val endMinute: Int,
    val label: String
)

object ShareHelper {
    private val gson = Gson()

    fun encodeSchedules(schedules: List<Schedule>): String {
        val sb = StringBuilder()
        for (i in schedules.indices) {
            val s = schedules[i]
            val label = s.label.replace("|", "").replace(";", "")
            sb.append("${s.dayOfWeek.value};${s.startHour};${s.startMinute};${s.endHour};${s.endMinute};$label")
            if (i < schedules.size - 1) sb.append("|")
        }

        val bytes = sb.toString().toByteArray(Charsets.UTF_8)
        val deflater = Deflater(Deflater.BEST_COMPRESSION)
        deflater.setInput(bytes)
        deflater.finish()
        val out = ByteArrayOutputStream()
        val buffer = ByteArray(1024)
        while (!deflater.finished()) {
            val count = deflater.deflate(buffer)
            out.write(buffer, 0, count)
        }
        deflater.end()

        val encoded = Base64.encodeToString(out.toByteArray(), Base64.NO_WRAP or Base64.URL_SAFE)
        return "v2:$encoded"
    }

    fun decodeSchedules(encodedString: String): List<ParsedScheduleEntry>? {
        if (encodedString.startsWith("v2:")) {
            return try {
                val base64Str = encodedString.removePrefix("v2:")
                val bytes = Base64.decode(base64Str, Base64.NO_WRAP or Base64.URL_SAFE)
                val inflater = Inflater()
                inflater.setInput(bytes)
                val out = ByteArrayOutputStream()
                val buffer = ByteArray(1024)
                while (!inflater.finished()) {
                    val count = inflater.inflate(buffer)
                    out.write(buffer, 0, count)
                }
                inflater.end()
                val decodedStr = String(out.toByteArray(), Charsets.UTF_8)
                parseDelimitedString(decodedStr)
            } catch (e: Exception) {
                e.printStackTrace()
                null
            }
        } else if (encodedString.contains(";") && encodedString.contains("|")) {
            // Support raw delimited string generated by AI
            return try {
                parseDelimitedString(encodedString.trim())
            } catch (e: Exception) {
                e.printStackTrace()
                null
            }
        } else {
            // Fallback to old format
            return try {
                val json = String(Base64.decode(encodedString, Base64.NO_WRAP))
                val type = object : TypeToken<List<SharedScheduleEntry>>() {}.type
                val entries: List<SharedScheduleEntry> = gson.fromJson(json, type)
                
                entries.map {
                    ParsedScheduleEntry(
                        day = it.day,
                        startHour = it.startHour,
                        startMinute = it.startMinute,
                        endHour = it.endHour,
                        endMinute = it.endMinute,
                        label = it.label
                    )
                }
            } catch (e: Exception) {
                e.printStackTrace()
                null
            }
        }
    }

    private fun parseDelimitedString(decodedStr: String): List<ParsedScheduleEntry> {
        val entries = mutableListOf<ParsedScheduleEntry>()
        if (decodedStr.isNotEmpty()) {
            val records = decodedStr.split("|")
            for (record in records) {
                val parts = record.split(";", limit = 6)
                if (parts.size == 6) {
                    entries.add(
                        ParsedScheduleEntry(
                            day = DayOfWeek.of(parts[0].toInt()),
                            startHour = parts[1].toInt(),
                            startMinute = parts[2].toInt(),
                            endHour = parts[3].toInt(),
                            endMinute = parts[4].toInt(),
                            label = parts[5]
                        )
                    )
                }
            }
        }
        return entries
    }
}
